// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GestionGastosContext))]
    [Migration("20250526135156_RenameGroupsToTeams")]
    partial class RenameGroupsToTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Expense", b =>
                {
                    b.Property<int>("IdExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_expense");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExpense"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(155)
                        .HasColumnType("varchar(155)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("'\"No description added.\"'");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("expense_name");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("IdExpense")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TeamId" }, "team_Id_idx");

                    b.HasIndex(new[] { "UserId" }, "user_id_idx");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("IdInvitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_invitation");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInvitation"));

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("int")
                        .HasColumnName("invited_user_id");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("IdInvitation")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TeamId" }, "fk_invitations_teams");

                    b.HasIndex(new[] { "InvitedUserId" }, "id_invited_idx");

                    b.HasIndex(new[] { "OwnerUserId" }, "owner_user_id_idx");

                    b.ToTable("invitations");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_team");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTeam"));

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("team_name");

                    b.HasKey("IdTeam")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OwnerId" }, "owner_id_idx");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("IdUser")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "phone_number_UNIQUE")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("UsersTeam", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("UserId", "TeamId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "TeamId" }, "teamId_idx");

                    b.HasIndex(new[] { "UserId" }, "userId_idx");

                    b.ToTable("users_teams", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Expense", b =>
                {
                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Expenses")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("team_Id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_id");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Domain.Entities.User", "InvitedUser")
                        .WithMany("InvitationInvitedUsers")
                        .HasForeignKey("InvitedUserId")
                        .IsRequired()
                        .HasConstraintName("invited_user_id");

                    b.HasOne("Domain.Entities.User", "OwnerUser")
                        .WithMany("InvitationOwnerUsers")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("owner_user_id");

                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("fk_invitations_teams");

                    b.Navigation("InvitedUser");

                    b.Navigation("OwnerUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany("Teams")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UsersTeam", b =>
                {
                    b.HasOne("Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("TeamId");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("userId");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("InvitationInvitedUsers");

                    b.Navigation("InvitationOwnerUsers");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
